services:
  postgres:
    image: postgres:17
    container_name: stocker-postgres
    environment:
      POSTGRES_DB: stocker
      POSTGRES_USER: stocker
      POSTGRES_PASSWORD: stocker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
